import cv2
back=cv2.imread('/home/student/Images/img45.jpg')
fore=cv2.imread('/home/student/Images/img7.jpg')
mask=cv2.imread('/home/student/Images/p4.jpg')
cv2.imshow("background",back)
cv2.imshow("foreground",fore)
cv2.imshow("mask",mask)
back=cv2.resize(back,(500,500))
fore=cv2.resize(fore,(500,500))
mask=cv2.resize(mask,(500,500))
bg=cv2.bitwise_and(fore,mask)
final=cv2.add(bg,back)
cv2.imshow("setup",final)
key=cv2.waitKey(0)
if (key==97):
    cv2.destroyAllWindows()